spring.application.name=reserve-service
server.port=8082

# NeonDB (PostgreSQL JPA)
spring.datasource.url=${NEONDB_URL}
spring.datasource.username=${NEONDB_USERNAME}
spring.datasource.password=${NEONDB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# HikariCP
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10

# Queue throttle (requests per second)
queue.throttle.rate=10

