server.port=8080

# Redis (docker 네트워크 내 컨테이너명)
spring.data.redis.host=redis

# 인터서비스 URL (Docker DNS)
user-service.base-url=http://user-service:8080
payment-service.base-url=http://payment-service:8080
