spring.application.name=reserve-service
server.port=8082

# JPA
spring.jpa.hibernate.ddl-auto=update

# Virtual Thread
spring.threads.virtual.enabled=true

# HikariCP
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Lettuce Connection Pool
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=32
spring.data.redis.lettuce.pool.max-idle=16
spring.data.redis.lettuce.pool.min-idle=8

spring.config.import=optional:classpath:database.properties
