spring.application.name=payment-service
server.port=8083

# JPA
spring.jpa.hibernate.ddl-auto=update

# Saga 학습용 랜덤 성공률 (0.0 ~ 1.0)
payment.success-rate=0.7

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.config.import=optional:classpath:database.properties
